version: "3.4"

services:

  pythonrpcserver:
    build:
      context: ./WebAPI
      dockerfile: ./pythonrpcserver.Dockerfile
  api:
    build:
      context: ./WebAPI
      target: publish
      dockerfile: ./API.Dockerfile
    
  taskengine:
    build:
      context: ./WebAPI
      target: publish
      dockerfile: ./TaskEngine.Dockerfile
    
  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: ./Dockerfile
